#
# 服务器配置
spring:
  # 配置文件
  profiles:
    # 激活
    active:
      - server-dev # 服务器 测试配置
      - eureka-dev # Eureka 测试配置
      - logging-dev # 日志 测试配置
      - native # 配置服务器使用本地配置（默认为 git 配置）
  application:
    # 在 Eureka Server 注册的服务名
    name: config
