#
# Redis-开发配置（供服务读取）
spring:
  redis:
    # 数据库名称，默认为 db0
    # 连接工厂使用的数据库索引。
    database: 5
    # Redis服务器主机。
    host: 127.0.0.1
    # redis服务器的登录密码。
    password:
    # Redis服务器端口。
    port: 6379
