#
# 数据源-开发配置（供服务读取）
spring:
  #
  # 数据库 配置
  datasource:
    #
    # 多数据源
    #
    # 没有@DS	      默认数据源
    # @DS("dsName")	  dsName可以为组名也可以为具体某个库的名称
    # 可以注解在方法上,可以注解在service实现或mapper接口方法上。
    dynamic:
      # 性能分析
      p6spy: true
      # 设置默认的数据源或者数据源组,默认值即为master,如果你主从默认下主库的名称就是master可不定义此项。
      primary: master
      # 开启 seata 代理，开启后默认每个数据源都代理，如果某个不需要代理可单独关闭
      seata: true
      strict: true
      # 支持XA及AT模式,默认AT
      seata-mode: AT
      datasource:
        # 主数据源
        master:
          # 驱动
          driver-class-name: com.mysql.cj.jdbc.Driver
          # 连接串
          url: jdbc:mysql://127.0.0.1:3306/spring-boot-cloud-hoxton?useSSL=false&serverTimezone=GMT%2B8
          # 用户名
          username: root
          # 密码，已加密，加密开头必须为：{cipher}，原文：root
          # 加密地址：/encrypt
          # 解密地址：/decrypt
          password: "{cipher}37fced378645ae2dac45a8f9eee922be897495baf3d142b8f32f1ddc699a9b01"
    #
    # Hikari 连接池
    hikari:
      # 最小空闲连接数量
      minimum-idle: 3
      # 连接池最大连接数
      maximum-pool-size: 10
