#
# seata-开发配置（供服务读取）
seata:
  # 关闭自动代理
  # https://dynamic-datasource.com/guide/tx/Seata.html#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9
  enable-auto-data-source-proxy: false
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: spring_boot_cloud_hoxton_group
  service:
    vgroup-mapping:
      spring_boot_cloud_hoxton_group: seata  #key与上面的tx-service-group的值对应
    grouplist:
      seata: localhost:8091 #seata-server地址仅file注册中心需要
  config:
    type: file
  registry:
    type: file
