#
# 跨域-开发配置
cors:
  default:
    # 允许路径，需要提供协议、端口
    add-mapping: /**
    # 允许跨域的域
    allowed-origins:
      - http://localhost:30001
      - http://localhost:10101
      - http://localhost:10201
      - http://localhost:10301
      - http://localhost:10401
      - http://localhost:10501
      - http://localhost:10601
      - http://localhost:10701
      - http://127.0.0.1:30001
      - http://127.0.0.1:10101
      - http://127.0.0.1:10201
      - http://127.0.0.1:10301
      - http://127.0.0.1:10401
      - http://127.0.0.1:10501
      - http://127.0.0.1:10601
      - http://127.0.0.1:10701
    # 允许跨域的方法
    allowed-methods:
      - GET
      - HEAD
      - POST
    # 时间，默认：1800 seconds (30 minutes)
    max-age: 1800
    # 允许携带凭证
    allow-credentials: true
