#
# Cookie CSRF-开发配置
csrf:
  cookie:
    default:
      # CSRF Cookie 是否为只读
      cookieHttpOnly: true
      # CSRF header 参数名
      headerName: X-XSRF-TOKEN
      # CSRF Cookie 名称
      cookieName: XSRF-TOKEN
      # CSRF 参数名
      parameterName: _csrf
      # CSRF Cookie 路径
      cookiePath:
