#
# Cloud-开发配置
spring:
  cloud:
    loadbalancer:
      ribbon:
        # 防止出现安全警告
        # 可设置本属性，或移除 spring-cloud-starter-netflix-ribbon（spring-cloud-starter-netflix-eureka-server 中引入了）
        # You already have RibbonLoadBalancerClient on your classpath.
        # It will be used by default.
        # As Spring Cloud Ribbon is in maintenance mode.
        # We recommend switching to BlockingLoadBalancerClient instead.
        # In order to use it, set the value of `spring.cloud.loadbalancer.ribbon.enabled` to `false` or remove spring-cloud-starter-netflix-ribbon from your project.
        enabled: false
