#
# Spring 配置
spring:
  # 配置文件
  profiles:
    # 激活
    active:
      - cloud-dev # Cloud-开发配置
      - eureka-dev # Eureka-开发配置
      - logging-dev # 日志-开发配置
      - server-dev # 服务器-开发配置
  application:
    # 在 Eureka Server 注册的服务名
    name: monitor
