#
# Cloud 测试配置
spring:
  cloud:
    config:
      # 表示已启用远程配置的标志。默认为true
      enabled: true
      # 发现属性
      discovery:
        # 指示已启用配置服务器发现的标志（将通过发现来查找配置服务器URL）。
        enabled: true
        # 用于找到配置服务器的服务ID。
        service-id: config
