#
# Eureka-开发配置
# https://docs.spring.io/spring-cloud-netflix/docs/2.2.6.RELEASE/reference/html/#spring-cloud-eureka-server-standalone-mode
eureka:
  # 实例
  instance:
    # 主机
    hostname: localhost
  # 客户端
  client:
    # eureka.client.register-with-eureka 与 eureka.client.fetch-registry 设置为 false，代表为 eureka server，
    # 防止自己注册自己
    register-with-eureka: false
    # 指示此客户端是否应从eureka服务器获取eureka注册表信息。
    fetch-registry: false
    # 可用区映射到与eureka服务器通信的标准URL列表。 每个值可以是单个URL或用逗号分隔的替代位置列表。
    # 通常，尤里卡服务器URL包含协议，主机，端口，上下文和版本信息（如果有）。
    # 示例：https://ec2-256-156-243-129.compute-1.amazonaws.com:7001/eureka/更改在运行时在由eurekaServiceUrlPollIntervalSeconds指定的下一个服务URL刷新周期生效。
    service-url:
      # Eureka 客户端设置 Eureka Server 的地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#
archaius:
  deployment:
    # 环境
    environment: 测试环境
